/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'service' : string,
  'customerName' : string,
  'requester' : Principal,
  'preferredBarber' : string,
  'appointmentTime' : Time,
  'phone' : string,
}
export interface Barber {
  'name' : string,
  'experience' : bigint,
  'specialty' : string,
}
export interface Service { 'name' : string, 'price' : bigint }
export interface Testimonial {
  'customerName' : string,
  'review' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'bookAppointment' : ActorMethod<
    [string, string, string, string, Time],
    bigint
  >,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAppointment' : ActorMethod<[bigint], Appointment>,
  'getAppointmentsByBarber' : ActorMethod<[string], Array<Appointment>>,
  'getBarbers' : ActorMethod<[], Array<Barber>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];