/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'customerName' : IDL.Text,
  'requester' : IDL.Principal,
  'preferredBarber' : IDL.Text,
  'appointmentTime' : Time,
  'phone' : IDL.Text,
});
export const Barber = IDL.Record({
  'name' : IDL.Text,
  'experience' : IDL.Nat,
  'specialty' : IDL.Text,
});
export const Service = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
export const Testimonial = IDL.Record({
  'customerName' : IDL.Text,
  'review' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
      [IDL.Nat],
      [],
    ),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  'getAppointmentsByBarber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getBarbers' : IDL.Func([], [IDL.Vec(Barber)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'customerName' : IDL.Text,
    'requester' : IDL.Principal,
    'preferredBarber' : IDL.Text,
    'appointmentTime' : Time,
    'phone' : IDL.Text,
  });
  const Barber = IDL.Record({
    'name' : IDL.Text,
    'experience' : IDL.Nat,
    'specialty' : IDL.Text,
  });
  const Service = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Nat });
  const Testimonial = IDL.Record({
    'customerName' : IDL.Text,
    'review' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time],
        [IDL.Nat],
        [],
      ),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
    'getAppointmentsByBarber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getBarbers' : IDL.Func([], [IDL.Vec(Barber)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };